// <auto-generated />
namespace SVM_Processor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class assessmentrevised : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assessmentrevised));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011548349_assessmentrevised"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
