// <auto-generated />
namespace SVM_Processor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class paymetterm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paymetterm));
        
        string IMigrationMetadata.Id
        {
            get { return "201708101513211_paymetterm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
