// <auto-generated />
namespace SVM_Processor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class family_backgroud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(family_backgroud));
        
        string IMigrationMetadata.Id
        {
            get { return "201706181419112_family_backgroud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
